function data = getdata()

%% Import data from text file.
% Script for importing data from the following text file:
%
%    /home/tom/Projects/corona/time_series_19-covid-Confirmed.csv
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2020/03/10 15:19:15

%% Initialize variables.
filename = 'time_series_19-covid-Confirmed.csv';
delimiter = ',';
startRow = 2;

%% Read columns of data as text:
% For more information, see the TEXTSCAN documentation.
formatSpec = '%*q%*q%*q%*q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'TextType', 'string', 'HeaderLines' ,startRow-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');

%% Close the text file.
fclose(fileID);

%% Convert the contents of columns containing numeric text to numbers.
% Replace non-numeric text with NaN.
raw = repmat({''},length(dataArray{1}),length(dataArray)-1);
for col=1:length(dataArray)-1
    raw(1:length(dataArray{col}),col) = mat2cell(dataArray{col}, ones(length(dataArray{col}), 1));
end
numericData = NaN(size(dataArray{1},1),size(dataArray,2));

for col=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48]
    % Converts text in the input cell array to numbers. Replaced non-numeric
    % text with NaN.
    rawData = dataArray{col};
    for row=1:size(rawData, 1)
        % Create a regular expression to detect and remove non-numeric prefixes and
        % suffixes.
        regexstr = '(?<prefix>.*?)(?<numbers>([-]*(\d+[\,]*)+[\.]{0,1}\d*[eEdD]{0,1}[-+]*\d*[i]{0,1})|([-]*(\d+[\,]*)*[\.]{1,1}\d+[eEdD]{0,1}[-+]*\d*[i]{0,1}))(?<suffix>.*)';
        try
            result = regexp(rawData(row), regexstr, 'names');
            numbers = result.numbers;
            
            % Detected commas in non-thousand locations.
            invalidThousandsSeparator = false;
            if numbers.contains(',')
                thousandsRegExp = '^[-/+]*\d+?(\,\d{3})*\.{0,1}\d*$';
                if isempty(regexp(numbers, thousandsRegExp, 'once'))
                    numbers = NaN;
                    invalidThousandsSeparator = true;
                end
            end
            % Convert numeric text to numbers.
            if ~invalidThousandsSeparator
                numbers = textscan(char(strrep(numbers, ',', '')), '%f');
                numericData(row, col) = numbers{1};
                raw{row, col} = numbers{1};
            end
        catch
            raw{row, col} = rawData{row};
        end
    end
end


%% Create output variable
timeseries19covidConfirmed = table;
timeseries19covidConfirmed.VarName5 = cell2mat(raw(:, 1));
timeseries19covidConfirmed.VarName6 = cell2mat(raw(:, 2));
timeseries19covidConfirmed.VarName7 = cell2mat(raw(:, 3));
timeseries19covidConfirmed.VarName8 = cell2mat(raw(:, 4));
timeseries19covidConfirmed.VarName9 = cell2mat(raw(:, 5));
timeseries19covidConfirmed.VarName10 = cell2mat(raw(:, 6));
timeseries19covidConfirmed.VarName11 = cell2mat(raw(:, 7));
timeseries19covidConfirmed.VarName12 = cell2mat(raw(:, 8));
timeseries19covidConfirmed.VarName13 = cell2mat(raw(:, 9));
timeseries19covidConfirmed.VarName14 = cell2mat(raw(:, 10));
timeseries19covidConfirmed.VarName15 = cell2mat(raw(:, 11));
timeseries19covidConfirmed.VarName16 = cell2mat(raw(:, 12));
timeseries19covidConfirmed.VarName17 = cell2mat(raw(:, 13));
timeseries19covidConfirmed.VarName18 = cell2mat(raw(:, 14));
timeseries19covidConfirmed.VarName19 = cell2mat(raw(:, 15));
timeseries19covidConfirmed.VarName20 = cell2mat(raw(:, 16));
timeseries19covidConfirmed.VarName21 = cell2mat(raw(:, 17));
timeseries19covidConfirmed.VarName22 = cell2mat(raw(:, 18));
timeseries19covidConfirmed.VarName23 = cell2mat(raw(:, 19));
timeseries19covidConfirmed.VarName24 = cell2mat(raw(:, 20));
timeseries19covidConfirmed.VarName25 = cell2mat(raw(:, 21));
timeseries19covidConfirmed.VarName26 = cell2mat(raw(:, 22));
timeseries19covidConfirmed.VarName27 = cell2mat(raw(:, 23));
timeseries19covidConfirmed.VarName28 = cell2mat(raw(:, 24));
timeseries19covidConfirmed.VarName29 = cell2mat(raw(:, 25));
timeseries19covidConfirmed.VarName30 = cell2mat(raw(:, 26));
timeseries19covidConfirmed.VarName31 = cell2mat(raw(:, 27));
timeseries19covidConfirmed.VarName32 = cell2mat(raw(:, 28));
timeseries19covidConfirmed.VarName33 = cell2mat(raw(:, 29));
timeseries19covidConfirmed.VarName34 = cell2mat(raw(:, 30));
timeseries19covidConfirmed.VarName35 = cell2mat(raw(:, 31));
timeseries19covidConfirmed.VarName36 = cell2mat(raw(:, 32));
timeseries19covidConfirmed.VarName37 = cell2mat(raw(:, 33));
timeseries19covidConfirmed.VarName38 = cell2mat(raw(:, 34));
timeseries19covidConfirmed.VarName39 = cell2mat(raw(:, 35));
timeseries19covidConfirmed.VarName40 = cell2mat(raw(:, 36));
timeseries19covidConfirmed.VarName41 = cell2mat(raw(:, 37));
timeseries19covidConfirmed.VarName42 = cell2mat(raw(:, 38));
timeseries19covidConfirmed.VarName43 = cell2mat(raw(:, 39));
timeseries19covidConfirmed.VarName44 = cell2mat(raw(:, 40));
timeseries19covidConfirmed.VarName45 = cell2mat(raw(:, 41));
timeseries19covidConfirmed.VarName46 = cell2mat(raw(:, 42));
timeseries19covidConfirmed.VarName47 = cell2mat(raw(:, 43));
timeseries19covidConfirmed.VarName48 = cell2mat(raw(:, 44));
timeseries19covidConfirmed.VarName49 = cell2mat(raw(:, 45));
timeseries19covidConfirmed.VarName50 = cell2mat(raw(:, 46));
timeseries19covidConfirmed.VarName51 = cell2mat(raw(:, 47));
timeseries19covidConfirmed.VarName52 = cell2mat(raw(:, 48));

%% Clear temporary variables
clearvars filename delimiter startRow formatSpec fileID dataArray ans raw col numericData rawData row regexstr result numbers invalidThousandsSeparator thousandsRegExp;

%%

data = timeseries19covidConfirmed;

%dataNL = timeseries19covidConfirmed(98,:);